# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 98988f40dd2ec82bce6f39af40861370cc33d8a76ce21a832506c8f3ef2e9d00aa3bcc6a32620974a81c65fe4bf2760604aa64c7b551401f38fd79d69629adaf

test:
  secret_key_base: 28058ebc5a2e0e796c8787cfd564cef14329461d9958807380a9fad74f599a21f2326635e88ed22654b90a2e868ff81c3f7966222070f34f21b9f7a36d2f96c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
